import "./globals.css"
import { Inter } from "next/font/google"

import Providers from "@/components/providers"
import ThemeBG from "@/components/themebg"

import DayInformation from "@/components/NavBar/DayInformation"
import MainNavBar from "@/components/NavBar/MainNavBar"
import SectionsMenu from "@/components/NavBar/SectionsMenu"

const inter = Inter({ subsets: ["cyrillic"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className + " px-8"}>
        <Providers>
          <ThemeBG />
          <nav className="flex items-center justify-between flex-wrap py-4">
            {/* day information */}
            <DayInformation />

            {/* Barra de separacion */}
            <div className="w-full h-2.5 bg-black dark:bg-gray-300/90 my-2" />

            {/* donaciones | logo | (search, user, theme)  
            // this or the next one have to be sticky 
            and stay on the top of page.

            Important thing is that the logo is always visible, user, theme and search
            
            */}
            <MainNavBar />

            {/* Barra de separacion */}
            <div className="w-full h-px bg-black dark:bg-gray-300/75 my-2" />

            {/* menu for more sections | sections...  */}
            <SectionsMenu />

            {/* Barra de separacion */}
            <div className="w-full h-px bg-black dark:bg-gray-300/75 my-2" />
          </nav>

          {children}
        </Providers>
      </body>
    </html>
  )
}
